name: Deploy Backend on Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Set Heroku Remote
        run: heroku git:remote -a adenjo6
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "adenjo6"
          heroku_email: "adenjo@ucsb.edu"
# name: Deploy Backend to Heroku

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.13'  

#       - name: Install backend dependencies
#         working-directory: ./backend
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Deploy to Heroku
#         working-directory: .
#         env:
#           HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#           HEROKU_APP_NAME: adenjo6
#         run: |
#           git config --global user.email "adenjo@ucsb.edu"
#           git config --global user.name "Aden"
#           git subtree push --prefix backend heroku main


