name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Heroku
        working-directory: .
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: adenjo6
        run: |
          git config --global user.email "adenjo@ucsb.edu"
          git config --global user.name "Aden"
          git subtree push --prefix backend heroku main